import Link from "next/link";
import { ArrowRight, Check, Cloud, Code2, Search, Sparkles } from "lucide-react";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { ContactForm, Faq, Solutions } from "../components/Interactive";
import { services } from "../data/services";

const solutions = [
  { t: "Lead Management", d: "Capture leads from your website, ads or forms, qualify them automatically, update your CRM and trigger personalized follow-ups.", flow: ["Lead", "AI Qualification", "CRM", "Follow-up", "Sales"] },
  { t: "Customer Support", d: "Create AI-assisted support systems that answer common questions, route complex requests and keep customer information synchronized.", flow: ["Customer", "AI Support", "Knowledge Base", "Human Escalation"] },
  { t: "SEO Growth Engine", d: "Build a structured SEO system around technical performance, search intent, content opportunities and ongoing optimization.", flow: ["Research", "Technical SEO", "Content", "Rankings", "Leads"] },
  { t: "Cloud Application", d: "Design, develop and deploy production-ready web applications on scalable AWS infrastructure.", flow: ["Next.js", "Node.js", "Database", "AWS", "Monitoring"] }
];
const principles = [["Business First", "Technology decisions start with the problem and expected outcome."], ["Built to Scale", "We design systems that can evolve as your users, data and operations grow."], ["Automation With Purpose", "We automate where it actually saves time, reduces friction or creates measurable value."], ["Clear Communication", "No unnecessary technical complexity. You understand what we're building and why."]];
const steps = [["Discover", "We understand your business, customers, workflows and the problem you want to solve."], ["Architect", "We define the strategy, technology stack, integrations, scope and measurable outcomes."], ["Build", "We develop, integrate and test with performance, usability and scalability in mind."], ["Launch & Improve", "We deploy, monitor and continuously improve using real-world performance and business data."]];
const faqs = [
  { q: "What does NasCore Technologies do?", a: "NasCore Technologies provides AI automation, SEO, modern web development and AWS cloud services for businesses looking to improve operations, digital visibility and scalability." },
  { q: "What business processes can you automate?", a: "We can automate lead capture, qualification, CRM updates, customer support, reporting, notifications, data synchronization and repetitive administrative workflows." },
  { q: "Do you build custom AI automation solutions?", a: "Yes. We design custom AI-powered workflows, integrations, assistants and automation systems based on specific business requirements." },
  { q: "Do you provide MERN and Next.js development?", a: "Yes. We build modern applications using React, Next.js, Node.js, Express, MongoDB and PostgreSQL depending on project requirements." },
  { q: "Can you deploy and manage applications on AWS?", a: "Yes. We work with EC2, S3, CloudFront, Route 53, Nginx, DNS and deployment pipelines." }
];
const icons = [Sparkles, Search, Code2, Cloud];
const orgSchema = { "@context": "https://schema.org", "@type": "Organization", name: "NasCore Technologies", url: "https://nascoretech.com", description: "AI automation, SEO, web development and AWS cloud solutions.", address: { "@type": "PostalAddress", addressLocality: "Karachi", addressCountry: "PK" } };

export default function Home() {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgSchema) }} />
    <Header />
    <main id="top">
      <section className="overflow-hidden bg-nas-charcoal text-white">
        <div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-6 sm:py-24 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:py-28">
          <div><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-nas-sand">AI · Automation · Development · Growth</p><h1 className="max-w-4xl text-4xl font-extrabold leading-[1.04] sm:text-5xl lg:text-7xl">We Build Digital Systems <span className="text-nas-sand">That Help Businesses Grow.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-white/65 sm:text-lg">NasCore Technologies combines AI automation, SEO, MERN & Next.js development, and AWS cloud solutions to help businesses automate repetitive work, build better digital products and scale reliably.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#contact" className="rounded-md bg-nas-sand px-6 py-4 text-center font-bold text-nas-charcoal transition hover:-translate-y-0.5 hover:bg-white">Start Your Project ↗</Link><Link href="#services" className="rounded-md border border-white/15 px-6 py-4 text-center font-bold text-white transition hover:border-nas-sand hover:text-nas-sand">Explore Services ↓</Link></div></div>
          <div className="rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-4 text-xs uppercase tracking-wider text-white/45"><span>The NasCore approach</span><span className="text-nas-sand">Build · Automate · Scale</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Leads", "Customer Data", "Manual Tasks", "Website Traffic", "AI Automation", "SEO Growth", "Cloud Systems", "Actionable Data"].map((x, i) => <div key={x} className={`rounded-lg border p-4 text-sm font-semibold ${i > 3 ? "border-nas-sand/30 bg-nas-sand/10 text-nas-sand" : "border-white/10 bg-black/10 text-white/70"}`}>{String(i + 1).padStart(2, "0")} · {x}</div>)}</div></div>
        </div>
      </section>

      <section id="services" className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-nas-copper">Core services</p><div className="mt-3 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-3xl font-extrabold sm:text-5xl">One Partner Across Your Digital Growth Stack</h2><p className="max-w-xl text-nas-muted">From automation to acquisition, product development and infrastructure, we build systems that work together.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{services.map((s, i) => { const Icon = icons[i]; return <article key={s.slug} className="group rounded-xl border border-nas-border bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-black/5 sm:p-8"><div className="flex items-center justify-between"><span className="text-sm font-bold text-nas-copper">{s.number}</span><Icon className="text-nas-copper" size={26} /></div><h3 className="mt-6 text-2xl font-extrabold">{s.title}</h3><p className="mt-4 leading-7 text-nas-muted">{s.description}</p><ul className="mt-6 grid gap-2 sm:grid-cols-2">{s.items.slice(0, 6).map(x => <li key={x} className="flex gap-2 text-sm text-nas-muted"><Check size={16} className="mt-0.5 shrink-0 text-nas-copper" />{x}</li>)}</ul><Link href={`/services/${s.slug}`} className="mt-7 inline-flex items-center gap-2 font-bold text-nas-copper">Explore {s.shortTitle} <ArrowRight size={17} /></Link></article> })}</div></div></section>

      <section className="bg-nas-charcoal py-20 text-white sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-nas-sand">One technology partner</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">Stop Managing Five Different Vendors</h2><p className="mt-6 max-w-xl leading-8 text-white/60">Your website, automation, search strategy and cloud infrastructure shouldn&apos;t operate as separate systems. NasCore brings them together.</p></div><div className="grid gap-3">{["Discovery & demand", "SEO + Website", "Lead / Customer", "AI Automation", "CRM / APIs", "AWS Cloud", "Growth"].map((x, i) => <div key={x} className="flex items-center gap-4 rounded-lg border border-white/10 bg-white/[.03] p-4"><span className="text-sm font-bold text-nas-sand">0{i + 1}</span><span className="font-semibold">{x}</span></div>)}</div></div></section>

      <section id="solutions" className="bg-nas-soft py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-nas-copper">Solutions</p><h2 className="mt-4 max-w-3xl text-3xl font-extrabold sm:text-5xl">What Can We Automate or Build For You?</h2><Solutions items={solutions} /></div></section>

      <section id="about" className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-nas-copper">About NasCore</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">Technology Should Solve Problems, Not Create New Ones</h2><p className="mt-6 leading-8 text-nas-muted">NasCore Technologies is a technology and digital growth company based in Karachi, Pakistan, helping businesses build, automate and scale through practical digital systems.</p></div><div className="grid gap-4 sm:grid-cols-2">{principles.map(([t, d]) => <div key={t} className="rounded-xl border border-nas-border bg-white p-6"><h3 className="text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-nas-muted">{d}</p></div>)}</div></div></div></section>

      <section id="process" className="bg-nas-charcoal py-20 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-nas-sand">How we work</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">From Idea to Working System</h2><ol className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map(([t, d], i) => <li key={t} className="rounded-xl border border-white/10 bg-white/[.03] p-6"><span className="text-sm font-bold text-nas-sand">0{i + 1}</span><h3 className="mt-5 text-xl font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-white/55">{d}</p></li>)}</ol></div></section>

      <section id="contact" className="bg-nas-soft py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-nas-copper">Have a project in mind?</p><h2 className="mt-4 text-3xl font-extrabold sm:text-5xl">Tell Us What&apos;s Slowing Your Business Down</h2><p className="mt-6 leading-8 text-nas-muted">Whether you need automation, stronger search visibility, a custom web application or scalable cloud infrastructure tell us what you&apos;re trying to achieve.</p></div><ContactForm /></div></section>

      <section className="py-20 sm:py-24"><div className="mx-auto max-w-4xl px-5 sm:px-6"><h2 className="text-3xl font-extrabold sm:text-5xl">Frequently Asked Questions</h2><div className="mt-8"><Faq items={faqs} /></div></div></section>
    </main>
    <Footer />
  </>
}
